### ISSUE TITLE
Cannot import angles on Ubuntu Trusty

### ISSUE THREAD

**Issue by mike-matera** [ros/angles#11] opened 2017-05-10 04:21 UTC
This is the same as issue #10 except it affects Ubuntu 14.04 (Trusty). I checked to be certain that I've got the latest packages installed. 

```bash
$ dpkg -l ros-indigo-angles 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  ros-indigo-angles         1.9.10-0trusty-20 amd64             This package provides a set of simple math utilities to 
```
Thanks for your help.

**Comment by tfoote** [comment] 2017-05-16 23:41
Duplicate of #10. This was fixed in 1.9.11 and in the sync on [May 10th](https://discourse.ros.org/t/new-packages-for-indigo-2017-05-11/1832?u=tfoote)

**Closed by tfoote** 2017-05-16 23:41 UTC
